    `define XRV_CCLUSTER_CACHE_LOCALPARAMS parameter L1I_WORD_SIZE_LP = 4, \
        parameter L1I_ADDR_WIDTH_LP	= (MEM_ADDR_WIDTH_P - `XM_CLOG2(L1I_WORD_SIZE_LP)), \
        parameter L1I_LINE_SIZE_LP	        = L1_LINE_SIZE_P, \
        parameter L1I_TAG_ID_BITS_LP	    = TID_WIDTH_LP, \
        parameter L1I_TAG_WIDTH_LP	        = (UUID_WIDTH_P + L1I_TAG_ID_BITS_LP), \
        parameter L1I_MEM_DATA_WIDTH_LP     = (L1I_LINE_SIZE_LP * 8), \
        parameter L1I_MEM_TAG_WIDTH_LP      = `CACHE_CLUSTER_MEM_TAG_WIDTH(L1I_MSHR_SIZE_P, 1, 1, NUM_L1I_CACHES_P, UUID_WIDTH_P), \
        parameter L1D_TAG_ID_BITS_LP        = `XM_CLOG2(8), \
        parameter L1D_TAG_WIDTH_LP	        = (UUID_WIDTH_P + L1D_TAG_ID_BITS_LP), \
        parameter L1D_WORD_SIZE_LP          = XLEN_P / 8, \
        parameter L1D_LINE_SIZE_LP          = L1_LINE_SIZE_P, \
        parameter L1D_MEM_DATA_WIDTH_LP     = (L1D_LINE_SIZE_LP * 8), \
        parameter L1D_MEM_TAG_WIDTH_LP      = `CACHE_CLUSTER_NC_MEM_TAG_WIDTH(L1D_MSHR_SIZE_P, L1D_NUM_BANKS_P, L1D_NUM_REQS_P, L1_NUM_MEM_PORTS_P, L1D_LINE_SIZE_LP, L1D_WORD_SIZE_LP, L1D_TAG_WIDTH_LP, SOCKET_SIZE_P, NUM_L1D_CACHES_P, UUID_WIDTH_P), \
        parameter L1_MEM_TAG_WIDTH_LP       = `XM_MAX(L1I_MEM_TAG_WIDTH_LP, L1D_MEM_TAG_WIDTH_LP), \
        parameter L1_MEM_ARB_TAG_WIDTH_LP   = (L1_MEM_TAG_WIDTH_LP + `XM_CLOG2(2)), \
        parameter L2_WORD_SIZE_LP           = L1_LINE_SIZE_P, \
        parameter L2_TAG_WIDTH_LP	        = L1_MEM_ARB_TAG_WIDTH_LP, \
        parameter L2_MEM_TAG_WIDTH_LP       = `CACHE_NC_MEM_TAG_WIDTH(L2_MSHR_SIZE_P, L2_NUM_BANKS_P, L2_NUM_REQS_P, L2_NUM_MEM_PORTS_P, L2_LINE_SIZE_P, L2_WORD_SIZE_LP, L2_TAG_WIDTH_LP, UUID_WIDTH_P)
